### ISSUE TITLE
vim/update.sh doesn't work for Neovim

### ISSUE THREAD

**Issue by astropanic** [nsf/gocode#310]
Since Neovim follows the XDG spec now ( ~/.vimrc is now ~/.config/nvim/init.vim, etc), ```vim/update.sh``` doesn't work anymore due to absence of the ```.vim``` directory

**Comment by nsf** [comment]
It's not supposed to work on anything but vim. In fact I've described everything script does in the README.md. Script is for convenience, it's not required. Frankly, I'm tired knowing a million ways of installing plugins on vim. Vim users, figure it out already.

**Comment by mogeiwang** [comment]
I have just copied ~/.vim/autoload/gocomplete.vim to ~/.config/nvim/, and it works like a charm.

**Comment by astropanic** [comment]
Of course it works this way, have you read the headline of the issue?

**Comment by nsf** [comment]
Anyways, if you guys want a separate script for neovim, just add it and submit a pull request. Whether you mention it in README.md or not, I don't have an opinion on that part. What (neo)vim needs is either a standard way to describe packages and a (semi-)official repository for packages or a convention. Even emacs has a package manager these days! As for me I find myself using Atom lately, where you just need to press a button to install a package. They use a `package.json` file in a root of a github repository which describes the package plus you need to upload your package to package registry explicitly.

**Comment by mogeiwang** [comment]
Shall we close this issue, since it has been fixed in [Pull request #311](https://github.com/nsf/gocode/pull/311)?

Besides, according to my tests, a single line of
`Plug 'nsf/gocode', { 'do': 'go get -u github.com/nsf/gocode;mkdir -p ~/.nvim/autoload;cp ~/.config/nvim/plugged/gocode/nvim/autoload/gocomplete.vim ~/.nvim/autoload/' }`
is enough if [plug](https://github.com/junegunn/vim-plug) is used in neovim. 

`Plug 'nsf/gocode', { 'do': 'go get -u github.com/nsf/gocode;mkdir -p ~/.vim/autoload;cp ~/.vim/plugged/gocode/vim/autoload/gocomplete.vim ~/.vim/autoload/' }`
may work for vim and [plug](https://github.com/junegunn/vim-plug) too. Although, I have not tested it, since I have uninstalled vim.
