### ISSUE TITLE
Cannot identify the local function name in a package

### ISSUE THREAD

**Issue by cosmtrek** [nsf/gocode#351]
![screen shot 2016-05-13 at 11 29 25](https://cloud.githubusercontent.com/assets/8832222/15275338/2c4d8b2a-1afb-11e6-9a96-9a36ae6e0fc0.png)

Could you see more details in this issue Shougo/neocomplete.vim#543 that I submitted a few days ago? Thanks very much!

**Comment by nsf** [comment]
Well, I'm on the other hand don't know if it's a gocode issue or not, because code looks simple enough and gocode should handle it. I can ask you to install some simple text editor like github.com/nsf/godit and try autocompletion there, if it also fails there - that might be a gocode's fault. Or another option is to use gocode's debug mode `gocode close && gocode -s -debug` and show me the dump of what it prints when you request autocompletion at the point of your interest.

In any case it would be nice to have a reproducable setup where I can inspect the bug myself if it's a bug.

**Comment by cosmtrek** [comment]
Thanks! I just install the godit and autocompletion works! I guess there's something wrong with my vim configuration. Sorry for your time.

BTW, I'm impressed by the view operation mode in your emacsish editor. Actually, I'm emacs fans. But emacs is becoming slow when more than 50 buffers opened. Sometimes I cannot endure it. Therefore, I takes few days to learn vim. Maybe I will back to emacs family 😄
