### ISSUE TITLE
Bug: kubernetes client does not complete

### ISSUE THREAD

**Issue by ghodss** [nsf/gocode#373]
With this program:

```
package main

import (
	"fmt"

	"k8s.io/client-go/1.4/kubernetes"
	"k8s.io/client-go/1.4/rest"
)

func main() {
	kc, err := kubernetes.NewForConfig(&rest.Config{
		Host: "http://10.1.2.3:8080",
	})
	if err != nil {
		fmt.Println(err)
	}
	kc.Core(). // <-- completion does not work here
}
```

The library this refers to is at https://github.com/kubernetes/client-go/.

**Comment by nsf** [comment]
Yes, appears to be a bug. As a guess - must be related to heavy import alias usage in the lib. Will take a look at it on weekend.

**Comment by zchee** [comment]
@ghodss @nsf 
I debug it.
Yes, it seems related to import alias.

In https://github.com/kubernetes/client-go/blob/master/1.4/kubernetes/typed/core/v1/componentstatus.go,

```go
package v1

import (
	api "k8s.io/client-go/1.4/pkg/api"
	v1 "k8s.io/client-go/1.4/pkg/api/v1"
	watch "k8s.io/client-go/1.4/pkg/watch"
)
```

package name is `v1`, also import `k8s.io/client-go/1.4/pkg/api/v1` with `v1` alias.
I'm surprised to be able to compile.

FYI, if rename
`k8s.io/client-go/1.4/kubernetes/typed/core/v1`
to
`k8s.io/client-go/1.4/kubernetes/typed/core/corev1`
```
rep "package v1" $GOPATH/src/k8s.io/client-go/1.4/kubernetes/typed/core/v1/*.go -l | xargs sed -i "s/package v1/package corev1/"
```
gocode will works fine.

So, maybe override package methods in this? (sorry, I don't know)
https://github.com/nsf/gocode/blob/master/package_bin.go#L168-L170

I hope that helps.

**Comment by nsf** [comment]
Interesting, was trying to solve the issue but no luck and one interesting point. The bug is valid even for Go 1.6 and hence gocode's text package parser (old one).

I took a look at the package and turns out Go doesn't expose package aliases. Which makes those import statements in the package file useless. My initial though was that they are here to introduce those aliases and gocode was built under an assumption that it's true. Internally gocode uses package aliases assuming that import format actually contains unique identifiers, but as you can see it doesn't.

```
$$
package kubernetes
        import glog "k8s.io/client-go/1.4/vendor/github.com/golang/glog"
        import fmt "fmt"
        import discovery "k8s.io/client-go/1.4/discovery"
        import rest "k8s.io/client-go/1.4/rest"
        import flowcontrol "k8s.io/client-go/1.4/pkg/util/flowcontrol"
        import v1beta1 "k8s.io/client-go/1.4/kubernetes/typed/authorization/v1beta1"
        import registered "k8s.io/client-go/1.4/pkg/apimachinery/registered"
        import v1 "k8s.io/client-go/1.4/kubernetes/typed/autoscaling/v1"
        import v1 "k8s.io/client-go/1.4/kubernetes/typed/batch/v1"
        import v1 "k8s.io/client-go/1.4/kubernetes/typed/core/v1"
        import v1beta1 "k8s.io/client-go/1.4/kubernetes/typed/extensions/v1beta1"
        import install "k8s.io/client-go/1.4/pkg/api/install"
        import install "k8s.io/client-go/1.4/pkg/apis/authorization/install"
        import install "k8s.io/client-go/1.4/pkg/apis/autoscaling/install"
        import install "k8s.io/client-go/1.4/pkg/apis/batch/install"
        import install "k8s.io/client-go/1.4/pkg/apis/extensions/install"
```

But on the other hand import format contains all the necessary info to parse the stuff.

Anyways the point is - it's a fundamental flaw in gocode which exists due to partly historical reasons, partly misunderstanding of how things work.

I guess I will fix that, but it may take quite some time. Essentially I need to change the way gocode stores package identifiers in the AST (I use AST to store semantic info during type resolve) and instead of making "path -> alias" lookups when parsing imported package and then doing the reverse when resolving types, I need to store paths directly in the identifiers and use "path -> alias" lookups only when printing stuff out (for the sake of pretty printing). Which is a smarter idea anyway.

**Comment by nsf** [comment]
To elabore more on the issue for those who is interested in historical reasons.

Initially Go had a very simple package description format which is super similar to actual Go source code. And in fact it is so similar that gocode's first package parser was built using regexp preprocessor and the result of preprocessing was fed to go/parser. And it worked fine for some time. Then the package format evolved and at some point I had to take their actual package parser and convert result it produces to the AST structure used in gocode. AST was used because as I said above, packages were parsed via go/parser which spits out AST.

And it made sense to me to make everything uniform, I have packages with some type info and I have currently edited file and other files of the currently edited package with some type info in them as well. So gocode just integrates everything into one AST structure with some scoping added on top of it and uses that to resolve the types. Hence artifacts like these. Because parsing actual source code gives me things like:

```
import omgwtfbbq "fmt"

func main() {
   omgwtfbbq.Println("hello, world")
}
```

And instead of transforming that AST into a friendlier for type analysis structure, gocode transforms package type info into similar AST. Which is a bloody stupid idea, but hey, you need to make a mistake to learn from it.

So yeah, whatever, I will fix it in 1-2 weeks maybe.

**Comment by nsf** [comment]
Should be fixed, but let me know if it's not.

As usual to update: `gocode close && go get -u github.com/nsf/gocode`
