### ISSUE TITLE
Autocomplete doesn't work in Emacs

### ISSUE THREAD

**Issue by proninyaroslav** [nsf/gocode#374]
Hello. go version go1.6.3 linux/amd64, Emacs. Autocomplete doesn't work for Go 1.6.3 (works on 1.5 - 1.6.2). 
My Emacs config:

``` emacs
(add-hook 'after-init-hook 'global-company-mode)
(require 'company-go)
(require 'go-mode-autoloads)
(add-hook 'go-mode-hook 'company-mode)
(add-hook 'go-mode-hook (lambda ()
                            (set (make-local-variable 'company-backends) '(company-go))
                            (company-mode)))
(add-hook 'go-mode-hook (lambda ()
                            (local-set-key (kbd \"M-.\") 'godef-jump)))
(setq gofmt-command "goimports")
(add-hook 'before-save-hook 'gofmt-before-save)
```

Steps for reproduce:
1) Import package (example: `fmt`)
2) Start to enter a function name (example: `fmt.Print...`)
As result, autocomplete doesn't tell the possible function name.

**Comment by syohex** [comment]
I cannot reproduce your issue. Did you use latest `gocode` ? Please reinstall and try again.

![gocode](https://cloud.githubusercontent.com/assets/554281/18137582/dcc9dcaa-6fe3-11e6-99aa-5f71d02c02b9.gif)

**Comment by proninyaroslav** [comment]
I reinstall `gocode` firstly, but it hasn't brought the expected results. I see this problem after updating to 1.6.3 (Fedora 24). Also i reinstall `company-go` and `auto-complete`.

**Comment by nsf** [comment]
When updating gocode, you need to kill the existing process by running `gocode close`, otherwise it keeps running. And README has the whole section on debugging.

**Comment by proninyaroslav** [comment]
@nsf 
I get the same result even after reboot.

**Comment by nsf** [comment]
Then read debug section in README. Seriously. TL;DR: in separate terminal window :

```
gocode close
gocode -s -debug
```

It will launch gocode server in debug mode, which shows info about every single autocompletion request. Including how it sees the submitted buffer, where the cursor position is, what imports got resolved and what didn't. If it doesn't print anything then the problem is with text editor, it doesn't invoke gocode.

**Comment by proninyaroslav** [comment]
@nsf 
I run gocode in a separate terminal and emacs in another. It doesn't print log. The problem in Emacs? 
Can you tell what is the reason? .config file above.

**Comment by nsf** [comment]
I don't see `(require 'company)` in it. As https://github.com/nsf/gocode/tree/master/emacs-company README says.

**Comment by proninyaroslav** [comment]
@nsf 
It didn't help. In addition, before it worked without it.

**Comment by nsf** [comment]
Do the older gocode versions work now? The most important part is to figure out where the problem comes from, gocode or emacs. As an option, try: https://github.com/nsf/godit, it's a simple emacs-like editor with no configuration, it supports gocode (but only on .go files which are saved on disk). If gocode works in godit and fails in emacs, then the problem is somewhere in emacs configuration.

**Comment by proninyaroslav** [comment]
@nsf 
I run godit in the terminal and it gave the same result as in Emacs.

**Comment by nsf** [comment]
Then I don't know how to help you.

**Comment by dineshbhosale** [comment]
`gocode` uses the output from `go install` to provide its suggestions. You have a few options to ensure you always get up-to-date suggestions:
 
- Always run `go install ./...` in your package when you make a change
- Run `gocode set autobuild true` to have gocode attempt to run `go install ./...` for you
- You can configure your task runner to run `go install ./...` command on every file save

**Comment by nsf** [comment]
@dineshbhosale For currently edited project gocode uses source files, no need to compile it. For imported packages however - yes, indeed.

**Comment by proninyaroslav** [comment]
After update I don't observe this problem. I think close this issue.
