### ISSUE TITLE
Code completions buggy in VSCode

### ISSUE THREAD

**Issue by Krognol** [nsf/gocode#387]
This was all done with Windows 10 64bit and Golang 1.7.1

So to start things off, what I mean by "buggy" is 
![code_2016-09-25_21-26-43](https://cloud.githubusercontent.com/assets/10560012/18817677/e9b0442c-8366-11e6-8ad6-72d1acb0e057.png)

A little annoying. I had this issue for a good while until I managed to resolve it... Temporarily.

I googled around and saw posts at the vscode-go repository that people had the same problem. The solutions listed were: run `gocode close` and/or `go get -u github.com/nsf/gocode`. I first tried doing what they told me. Without closing VSCode, I closed `gocode` and updated it, then went back and tried getting the code completion again. Still the same problem. 

Next thing I tried was to close gocode manually, then exit VSCode and then update gocode. After relaunching, the same problem was there. 

Running out of options I decided to try to close gocode manually and then run gocode with an invalid parameter, in this case `gocode open`. Surprisingly, it worked, and fixed the problem until I closed VSCode, or ran `go run main.go` in the integrated terminal.

Then I also tried to run gocode with a valid parameter, which in this case was `gocode -h`, even more surprisingly, this did NOT fix the problem.

Very strange.

EDIT: I should add that I always opened the same files.

**Comment by nsf** [comment]
It's possible that VSCode has its own version of gocode somewhere. Not sure about that. You can always try to debug the gocode by launching the process manually in a separate console window via: 

```
gocode close
gocode -s -debug
```

This way when you do autocompletion requests and given that your text editor actually uses this instance of gocode, you'll see panic stack traces. If you can get there, paste the panic stack trace here and perhaps I can tell you what's wrong.

**Comment by Krognol** [comment]
Apparently running `gocode -s -debug` also fixes the problem, so I can't get a panic. I'm not quite sure what's happening.

**Comment by nsf** [comment]
Hm, it's possible that there are two gocode binaries on your system. Sadly I can't tell how to find them on windows. On linux you can do `which -a gocode` and it will list all gocode binaries in PATH. Perhaps VSCode uses it's own version of gocode which is slightly older than the most recent gocode version.

What happens is that when you launch gocode manually, the gocode version used by a text editor sees the server and just talks to it, instead of running itself as a server. As a result you get autocompletions from the proper version. 

So, all I can tell here is this. Try to figure out where is the gocode binary that editor launches and whether it's the latest version you compiled or not. Maybe in process explorer you can find the actual binary location, not sure about that. I don't use windows very often.

**Comment by Krognol** [comment]
Running `WHERE /R C:\ gocode*` only lists one gocode executable in the `C:\Go\bin` directory, so I'm not quite sure how to figure out what gocode VSCode is running.

**Comment by nsf** [comment]
https://github.com/Microsoft/vscode-go/blob/master/src/goPath.ts

VSCode's go plugin does some nasty searching for the binary on his own, so "where" or "which" won't give reliable results.

Well, take a look at GOPATH/bin dir then in your PATH (which is shown by WHERE), then in your GOROOT/bin. As the source file above suggests.

**Comment by Krognol** [comment]
I deleted the gocode binary from my GOROOT, and now it works again. There were a gocode binary in the GOROOT and the GOPATH.

**Comment by nsf** [comment]
ok, great.
