### ISSUE TITLE
providing a snippet if err != nil ?

### ISSUE THREAD

**Issue by southwolf** [nsf/gocode#406]
Since `if err != nil` is so widely used in Go, why not provide a quick snippet for that?

**Comment by dominikh** [comment]
Because that's your editor's job, not that of gocode.

**Comment by nsf** [comment]
What @dominikh said. Sorry, main gocode's task is to provide type aware info. Keywords or syntax constructions is none of its business. The reason why gocode provides completion for built-in types (such as int), is because you can shadow them by your own entities: https://play.golang.org/p/JIFCBIVi_u, and gocode will be able to tell you. Keywords and such on the other hand always stay relevant and there is no need for any kind of semantical evaluation.
