### ISSUE TITLE
package was not recognized when function has return signature

### ISSUE THREAD

**Issue by kovetskiy** [nsf/gocode#475]
Hello, today I found a bug where gocode doesn't recognizes package when context function returns something.
I've added testcases to show where is the problem:
https://github.com/nsf/gocode/compare/master...kovetskiy:master

I've added debug prints and now I see that in 2nd testcase cursor_context recognized as struct field:
testcase 0061:
```
XXXXXX autocompletecontext.go:362 cc: main.cursor_context{decl:(*main.decl)(nil), partial:"fmt", struct_field:false, decl_import:false, expr:ast.Expr(nil)}
```
testcase 0062:
```
XXXXXX autocompletecontext.go:362 cc: main.cursor_context{decl:(*main.decl)(0xc420170460), partial:"fmt", struct_field:true, decl_import:false, expr:ast.Expr(nil)}
```

**Comment by nsf** [comment]
Yes, thanks for the report. I kind of know about this bug. Gocode by mistake thinks that the function body is a struct literal. E.g. `func Foo() *Some { ... }` is considered as `Some{ ... }`. So it tries to look for autocompletion candidates within struct fields instead.

Probably I can fix that by doing a smarter lookahead (or actually "lookback" in this case).

**Comment by kovetskiy** [comment]
@nsf it will be perfect.

**Comment by kovetskiy** [comment]
@nsf is there any workaround to fix this?

**Comment by nsf** [comment]
No, there is no simple fix. You can rip off this code: https://github.com/nsf/gocode/blob/master/cursorcontext.go#L371-L391, but it will disable struct literal field autocompletion. A proper way to fix it is to make it so that this function understands the difference between a struct literal and a function literal. https://github.com/nsf/gocode/blob/master/cursorcontext.go#L126-L157. Gocode does backwards parsing there, it's hard to say how to do it properly without thinking a lot. Probably a quick hack would be to inspect few more tokens back. If it's a `*` here, then it's definitely not a struct literal. If it's `)` there, also not a struct literal. Might be enough for most cases. I'll try to add it this evening.

**Comment by nsf** [comment]
Just pushed a fix, try it out and let me know if it works for you.

**Comment by kovetskiy** [comment]
@nsf yeah, it works now, thank you!
