### ISSUE TITLE
gocode gives incorrect completions in a position after unicode characters

### ISSUE THREAD

**Issue by ramya-rao-a** [nsf/gocode#489]
From https://github.com/Microsoft/vscode-go/issues/1431 by @dc0d

Sample code where the issue repros is [here](https://gist.github.com/dc0d/fa6d4349cf4415df3c44cdb8fb024328)

`gocode` gives correct completions when triggered above the line with unicode chars in the above example, but not in the line after it

Screenshots for this issue from vscode is [here](https://github.com/Microsoft/vscode-go/issues/1431#issuecomment-354622825)

Output of the `gocode` cmd for this issue is [here](https://github.com/Microsoft/vscode-go/issues/1431#issuecomment-354625199)

**Comment by DisposaBoy** [comment]
@ramya-rao-a Are you sure the offsets are correct?

After adding `\tlog.` to your code `...fmt.Println(len(s), utf8.RuneCount(s))` tells me the offsets are `266` and `c158`. This is also confirmed by printing what GoSublime uses and I can't reproduce the issue in either GoSublime or using gocode directly.

If VS Code gives you the offsets in `bytes` (unlike Sublime Text), when you pass `c123` to gocode, the completion will be wrong. So in that case you'd need to pass `123` instead of `c123`.

**Comment by nsf** [comment]
I should correct gocode docs though. Gocode uses either **unicode code points** as offset or **bytes**. Never unicode characters. There is a similar issue: https://github.com/nsf/gocode/issues/460. I don't think I'll do anything about this on my end, except making docs more clear. Other editors use "c" prefix and send unicode code points already. Plus calculating proper unicode characters offset is complicated (maybe).

**Comment by ramya-rao-a** [comment]
> If VS Code gives you the offsets in bytes (unlike Sublime Text), when you pass c123 to gocode, the completion will be wrong. So in that case you'd need to pass 123 instead of c123.

@DisposaBoy You are right here. VS Code is not passing the byte offset but is using the `c` prefix.

@dc0d To confirm this, can you try the below?
- Edit the file ~/.vscode/extensions/lukehoban.go-0.6.70/out/src/goSuggest.js` to remove the `c` prefix that is added. Look for `'c' + offset`
- Save the file, reload VS Code that has you Go code and try auto-completion
