### ISSUE TITLE
Move gocode to github organization?

### ISSUE THREAD

**Issue by sergey-shambir** [nsf/gocode#533]
Now the primary fork is https://github.com/mdempsky/gocode
But there is alternative way to transfer maintenance.
You can create Github organization and add mdempsky as (admin) member.
In this case, whole repository can be moved to the organization and github will redirect from old URL.

**Comment by mattn** [comment]
[This](https://github.com/stamblerre/gocode) too.

**Comment by stamblerre** [comment]
We are currently working on a LSP implementation that will ultimately replace gocode in its many forms (https://github.com/golang/tools/tree/master/cmd/golsp). We apologize for the confusion with the different forks, but we will be keeping this structure until the LSP is ready.

**Comment by sergey-shambir** [comment]
Good news!
On the other hand, it's still better to transfer repository: `gocode` will be used for years until `golsp` will completely replace it for all tools and editors.

**Comment by nsf** [comment]
> gocode will be used for years until

I hope not.

I'm not doing anything with this repository, the goal is not to keep maintaining gocode, but to kill it. Doing nothing forces people to look for alternatives more actively and maybe even actually doing something as you can see with this LSP project.

I explained it a couple of times. Gocode was written very long time ago (2009-2010) as a simple hack. Since then, architecture never improved. People tend to think that gocode is this big and important software. It's not. Something like gocode can be written in a month if working on it full time. I want better tools for Go, sadly core Go devs are not very interested in them, otherwise they'd do it long time ago. However, now they have Go tools team. Send all kinds of letters with wishes to those guys and gals.
